future: true
permalink: /:title/
url: http://blog.xyecho.com
name: xyecho
author: xyecho
email: 1447675994@qq.com
duoshuo: xyecho
beian: 
cnzz: 
weibo: fangshenghui
github: CarlosFang
paginate: 20
highlighter: rouge
truncate: true
about: "xyecho(xyecho)"
plugins: [jekyll-paginate]